const mukattaData = [
    { name: "Bakara", id: 2, start: "Elif Lam Mim", counts: "ا: 1, ل: 1, م: 1" },
    { name: "Âl-i İmrân", id: 3, start: "Elif Lam Mim", counts: "ا: 1, ل: 1, م: 1" },
    { name: "A'râf", id: 7, start: "Elif Lam Mim Sad", counts: "ا: 1, ل: 1, م: 1, ص: 1" },
    { name: "Yûnus", id: 10, start: "Elif Lam Ra...", counts: "ا: 2, ل: 4, ر: 1, ... (Tüm Ayet)" },
    { name: "Hûd", id: 11, start: "Elif Lam Ra...", counts: "ا: 2, ل: 3, ر: 2, ... (Tüm Ayet)" },
    { name: "Yûsuf", id: 12, start: "Elif Lam Ra...", counts: "ا: 2, ل: 4, ر: 1, ... (Tüm Ayet)" },
    { name: "Ra'd", id: 13, start: "Elif Lam Mim Ra...", counts: "ا: 4, ل: 10, م: 3, ر: 3, ... (Tüm Ayet)" },
    { name: "İbrâhîm", id: 14, start: "Elif Lam Ra...", counts: "ا: 2, ل: 12, ر: 5, ... (Tüm Ayet)" },
    { name: "Hicr", id: 15, start: "Elif Lam Ra...", counts: "ا: 3, ل: 3, ر: 2, ... (Tüm Ayet)" },
    { name: "Meryem", id: 19, start: "Kaf Ha Ya Ayn Sad", counts: "ك: 1, ه: 1, ي: 1, ع: 1, ص: 1" },
    { name: "Tâhâ", id: 20, start: "Tâ Hâ", counts: "ط: 1, ه: 1" },
    { name: "Şuarâ", id: 26, start: "Tâ Sîn Mîm", counts: "ط: 1, س: 1, م: 1" },
    { name: "Neml", id: 27, start: "Tâ Sîn...", counts: "ط: 1, س: 1, ... (Tüm Ayet)" },
    { name: "Kasas", id: 28, start: "Tâ Sîn Mîm", counts: "ط: 1, س: 1, م: 1" },
    { name: "Ankebût", id: 29, start: "Elif Lam Mim", counts: "ا: 1, ل: 1, م: 1" },
    { name: "Rûm", id: 30, start: "Elif Lam Mim", counts: "ا: 1, ل: 1, م: 1" },
    { name: "Lokmân", id: 31, start: "Elif Lam Mim", counts: "ا: 1, ل: 1, م: 1" },
    { name: "Secde", id: 32, start: "Elif Lam Mim", counts: "ا: 1, ل: 1, م: 1" },
    { name: "Yâsîn", id: 36, start: "Yâ Sîn", counts: "ي: 1, س: 1" },
    { name: "Sâd", id: 38, start: "Sâd...", counts: "ص: 1, ... (Tüm Ayet)" },
    { name: "Mü'min", id: 40, start: "Hâ Mîm", counts: "ح: 1, م: 1" },
    { name: "Fussilet", id: 41, start: "Hâ Mîm", counts: "ح: 1, م: 1" },
    { name: "Şûrâ", id: 42, start: "Hâ Mîm", counts: "ح: 1, م: 1" },
    { name: "Zuhruf", id: 43, start: "Hâ Mîm", counts: "ح: 1, م: 1" },
    { name: "Duhân", id: 44, start: "Hâ Mîm", counts: "ح: 1, م: 1" },
    { name: "Câsiye", id: 45, start: "Hâ Mîm", counts: "ح: 1, م: 1" },
    { name: "Ahkaf", id: 46, start: "Hâ Mîm", counts: "ح: 1, م: 1" },
    { name: "Kâf", id: 50, start: "Kâf...", counts: "ق: 2, ... (Tüm Ayet)" },
    { name: "Kalem", id: 68, start: "Nûn...", counts: "ن: 2, ... (Tüm Ayet)" }
];
